Small changes

diff --git a/filter/list_good_files b/filter/list_good_files
--- a/filter/list_good_files
+++ b/filter/list_good_files
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ "$#" == 0 ]; then
+    echo "Error, not enough args"
+    exit 1
+fi
+
 find "$1" -print0 | ./filter -z ./predicat
 
 exit 0
